### ISSUE TITLE
Command Line Issues

### ISSUE THREAD

**Issue by aop4** [coursera/courseraoauth2client#6]
Hi Chris! I've been having an issue with your application. I registered my application with Coursera and am following your instructions to the tee. When the program prompts me for the client id and client secret, I enter those given by Coursera. Then it says ```Please enter the requested scopes of the app not including "view_profile", separated by whitespace.``` The only scope we're requesting from Coursera is view_profile, and we definitely don't want to use the only other scope available, which allows you to communicate with users through Coursera. So naturally we shouldn't type anything here, right? But I get an error message if I simply hit enter:

```
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/main.py", line 64, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/commands/config.py", line 36, in authorize
    oauth2_instance = oauth2.build_oauth2(args.app, args)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 472, in build_oauth2
    configure_app(app, cfg)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 517, in configure_app
    with open(cfg_path, 'wb') as configfile:
IOError: [Errno 2] No such file or directory: '/home/andrew/.coursera/courseraoauth2client.cfg'
```

**Comment by ckozin** [comment]
I don't know if you have found your answer or not, but in case others have this issue, the solution that worked for me was to create the directory .coursera in the user's home directory.

**Comment by dhruvd25** [comment]
Yes, I can confirm that the above comment is accurate. Used
`mkdir home/username/.coursera` in the folder and I was able to authenticate it.
